language: go

dist: focal

os:
  - linux
  - osx
  - windows

arch:
  - amd64
  - i386
  - arm64

go:
  - "1.18"
  - "1.17"
  - "1.16"
  - "1.15"
  - "1.14"

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

#after_success:
#  - test "$TRAVIS_OS_NAME" = linux && test "$TRAVIS_CPU_ARCH" = amd64 && test "$TRAVIS_GO_VERSION" = "1.18" && export CODECOV_UPLOAD=yes
#  - test $CODECOV_UPLOAD = "yes" && bash <(curl -s https://codecov.io/bash)
