name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        go-ver: ["1.23", "1.22", "1.21", "1.20", "1.19"]
        include:
          - os: "ubuntu-latest"
            go-ver: "1.23"
            cover: true

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-ver }}

      - name: Build
        run: go build -v ./...

      - name: Test with Cover
        run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...
        if: ${{ matrix.cover }}

      - name: Test without Cover
        run: go test -v ./...
        if: ${{ !matrix.cover }}

      - name: Test Race
        run: go test -race -v ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        if: ${{ matrix.cover }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

